{{- range $serviceName, $service := .Values.services }}
{{ if $service.configs }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.name }}-{{ $serviceName }}-config-{{ template "rand" . }}
data:
{{- range $service.configs }}
  {{ .name }}: {{ quote .value }}
{{- end }}

---
{{ end }}
{{ end }}