{{- range $serviceName, $service := .Values }}

{{ if ne $serviceName "global" }}
{{ if $service.configs }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name  }}-{{ $serviceName }}-config-{{ template "rand" . }}
data:
{{- range $service.configs }}
  {{ .name }}: {{ quote .value }}
{{- end }}

---
{{ end }}
{{ end }}
{{ end }}