{{- range $serviceName, $service := .Values }}

{{ if ne $serviceName "global" }}
{{ if $service.dapr }}
{{ if or $service.dapr.auth $service.dapr.tracing }}

apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ $.Release.Name  }}-{{ $serviceName }}-dapr-config-{{ template "rand" . }}
spec:
{{ if $service.dapr.auth }}
  httpPipeline:
    handlers:
    - name: {{ $.Release.Name  }}-{{ $serviceName }}-oauth2-{{ template "rand" . }}
      type: middleware.http.oauth2clientcredentials
{{ end }}
{{ if $service.dapr.tracing }}
  tracing:
    samplingRate: {{ quote $service.dapr.tracing.samplingRate | default "1" }}
    zipkin:
      endpointAddress: {{ quote $service.dapr.tracing.endpointAddress | default "http://zipkin.tracing.svc.cluster.local:9411/api/v2/spans" }} 
{{ end }}

---
{{ end }}
{{ end }}
{{ end }}
{{ end }}