{{- range $serviceName, $service := .Values }}

{{ if not eq $serviceName "global" }}
{{ if $service.dapr }}
{{ if $service.dapr.auth }}

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ $.Release.Name  }}-{{ $serviceName }}-oauth2-{{ template "rand" . }}
spec:
  type: middleware.http.oauth2clientcredentials
  version: v1
  metadata:
  - name: clientId
    value: {{ $service.dapr.auth.clientId }}
  - name: clientSecret
    secretKeyRef:
      name: {{ $.Release.Name  }}-{{ $serviceName }}-secret-{{ template "rand" . }}
      key: {{ $service.dapr.auth.clientSecretKey }}
  - name: scopes
    value: {{ $service.dapr.auth.scopes }}
  - name: tokenURL
    secretKeyRef: 
      name: identity
      key: token-url
  - name: headerName
    value: "authorization"
  - name: authStyle
    value: 0
---

{{ end }}
{{ end }}
{{ end }}
{{ end }}
