{{- range $serviceName, $service := .Values }}
{{ if $service.endpoint }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ $.Release.Name  }}-{{ $serviceName }}
spec: 
  rules: 
  - host: {{ $service.endpoint.host }}
    http: 
      paths: 
      - backend: 
          service:
            name: {{ $.Release.Name  }}-{{ $serviceName }}-dapr
            port:
              number: 80
        path: /v1.0
        pathType: ImplementationSpecific
      - backend: 
          service:
            name: {{ $.Release.Name  }}-{{ $serviceName }}
            port: 
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts: 
    - {{ $service.endpoint.host }}
    secretName: {{ $service.endpoint.tlsSecret | default "dk-region-ru" }}
---

{{ end }}
{{ end }}