{{- range $serviceName, $service := .Values.services }}
{{ if $service.endpoint }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ $.Values.name }}-{{ $serviceName }}
spec: 
  rules: 
  - host: {{ $service.endpoint.host }}
    http: 
      paths: 
      - backend: 
          serviceName: {{ $.Values.name }}-{{ $serviceName }}-dapr
          servicePort: 80
        path: /v1.0
        pathType: ImplementationSpecific
      - backend: 
          serviceName: {{ $.Values.name }}-{{ $serviceName }}
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts: 
    - {{ $service.endpoint.host }}
    secretName: {{ $service.endpoint.tlsSecret | default "dk-region-ru" }}
---

{{ end }}
{{ end }}