{{ range $.Values.services }}
{{ if .secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $.Values.name }}-{{ .name }}-secret-{{ template "rand" . }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
  {{- range .secrets }}
    {{ .name }}: {{ quote .value }}
  {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $.Values.name }}-{{ .name }}-secret-{{ template "rand" . }}
    type: Opaque
---
{{ end }}
{{ end }}