{{- range $serviceName, $service := .Values }}

{{ if ne $serviceName "global" }}
{{ if $service.secrets }}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $.Release.Name  }}-{{ $serviceName }}-secret-{{ template "rand" . }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
  {{- range $service.secrets }}
    {{ .name }}: {{ quote .value }}
  {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $.Release.Name  }}-{{ $serviceName }}-secret-{{ template "rand" . }}
    type: Opaque
---

{{ end }}
{{ end }}
{{ end }}