{{- range $serviceName, $service := .Values }}

{{ if ne $serviceName "global" }}
{{ if $service.endpoint }}

kind: Service
apiVersion: v1
metadata: 
  name: {{ $.Release.Name  }}-{{ $serviceName }}
  labels: 
    app: {{ $.Release.Name  }}-{{ $serviceName }}
spec: 
  selector: 
    app:  {{ $.Release.Name  }}-{{ $serviceName }}
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---

{{ end }}
{{ end }}
{{ end }}